# Generated by Django 5.1.1 on 2024-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='google_place_id',
            new_name='place_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='cuisine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vicinity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
