# Generated by Django 5.1.1 on 2024-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='place_id',
            new_name='google_place_id',
        ),
    ]
