# Generated by Django 4.2.15 on 2024-09-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0002_rename_google_place_id_favorite_place_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='google_place_id',
            new_name='place_id',
        ),
    ]
